services:
  linkinzzz-bot:
    image: ghcr.io/duckinzzz/linkinzzz-bot:latest
    container_name: linkinzzz-bot
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8081"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ./insta_cookies.txt:/app/insta_cookies.txt:ro
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.20
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook_link.rule=Host(`webhook.duckinzzz.ru`) && PathPrefix(`/linkinzzz`)"
      - "traefik.http.routers.webhook_link.entrypoints=websecure"
      - "traefik.http.routers.webhook_link.tls=true"
      - "traefik.http.services.webhook_link.loadbalancer.server.port=8081"

networks:
  proxy:
    external: true